### ISSUE TITLE
Add a Github action to check unwanted files in PRs

### ISSUE THREAD

**Issue by livingsilver94** [snekpit/main#2]
Just like commit hooks for those with commit privileges, PRs should be guarded by Github actions. PRs shall not include binary files (like .stone files) or other left over files unrelated to packages.

**Comment by ikeycode** [comment]
@der-eismann ideas? :D

**Comment by der-eismann** [comment]
Hmm, first idea would be something like `for each entry in manifest.jsonc | jq .packages[].files` do a `grep` over the repo to look for duplicates. But I'm sure there is a more elegant solution :smile:

**Comment by ermo** [comment]
Migrated to serpent-os/recipes
