### ISSUE TITLE
Strace can be built with LLVM

### ISSUE THREAD

**Issue by livingsilver94** [snekpit/main#3]
See this comment: https://github.com/snekpit/main/blob/c2b8ffb7f5bdcb327257199724b3948eebf37ddd/devel/strace/stone.yml#L11

Yet  I managed to build strace using LLVM: https://github.com/snekpit/venom/blob/main/dev-utils/strace/stone.yml

Unless it proved to be buggy, we're not locked to using the GNU toolchain.

**Comment by ReillyBrogan** [comment]
I haven't moved `strace` over from venom yet, would you like to do the honors with a PR? You can put any testing/etc you've done to make your case.
