### ISSUE TITLE
Add terminus console fonts and make /etc/vconsole.conf stateless

### ISSUE THREAD

**Issue by ermo** [snekpit/main#50]
> **Ikey Doherty**
> OK check file list of kbd
> Rundep it to systemd
> Provide stateless vconsole defaults via patch 
> And fix kconfig
> Bout right?

See https://github.com/serpent-os/moss/issues/32 for overarching goals.

Basically depends on setting `CONFIG_FONT_TER16x32` (which is the CP-437 `ter-i32n` font) in the kernel config and then setting `FONT=ter-v32n` + a UTF-8 capable locale by default.

**Comment by ikeycode** [comment]
This only lacks vconsole.conf now fwiw.

**Comment by ReillyBrogan** [comment]
I'm not sure that a rundep for systemd is the right approach. That will pull it in for container images that pull in systemd which is probably not desirable. I think it would be better as a rundep of a virtual package for a minimal system instead.

**Comment by ermo** [comment]
> I'm not sure that a rundep for systemd is the right approach. That will pull it in for container images that pull in systemd which is probably not desirable. I think it would be better as a rundep of a virtual package for a minimal system instead.

Perhaps the kernel should rundep on it, assuming that we set all kernel builds to use terminus VGA fonts as well?

That way, if a system has a kernel, great, it gets terminus fonts. 

If it doesn't, great, it doesn't (= the container case).

**Comment by ermo** [comment]
Migrated to serpent-os/recipes
