### ISSUE TITLE
Immediate: Get all packages up to date and secure

### ISSUE THREAD

**Issue by ikeycode** [snekpit/main#99]
We have a pressing need to get production ready docker base images for infrastructure, as well as shift into alpha ISOs stage.
To do that, we need the base cleaned up and updated, while we bring moss-rs up and boulder-rs into existence.

For now it's sufficient to use legacy moss/boulder until such time as we announce the shift and get the infrastructure over to the
Rust versions. This will be very soon for moss-rs.

**Comment by ermo** [comment]
Migrated to serpent-os-/recipes
